import { signIn } from 'next-auth/react'
import Head from 'next/head'
import Image from 'next/image'
import React from 'react'

const Login = () => {
  return (
    <div className="flex justify-center items-center flex-col mt-36 space-y-10">
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Facebook_Logo_%282019%29.png/800px-Facebook_Logo_%282019%29.png"
        />
      </Head>
      <Image width={500} height={500} src="/logoSm.jpg" alt="logo" />
      <h1
        onClick={() => signIn()}
        className="px-10 py-5 bg-blue-600 cursor-pointer text-white rounded-full font-medium text-center">
        Login with facebook
      </h1>
    </div>
  )
}

export default Login
